# Generated by Django 4.2.2 on 2023-07-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('enc_data', models.BigIntegerField()),
                ('op_time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
