# Generated by Django 4.2.2 on 2023-08-08 13:27

import VoteXX.datatypes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VoteXX_auth', '0001_initial'),
        ('VoteXX', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToyElection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('help_email', models.EmailField(max_length=254, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoteXX_auth.user')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, VoteXX.datatypes.LDObjectContainer),
        ),
        migrations.CreateModel(
            name='VoterFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_file', models.FileField(max_length=250, null=True, upload_to='voters/%Y/%m/%d')),
                ('voter_file_content', models.TextField(null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processing_started_at', models.DateTimeField(null=True)),
                ('processing_finished_at', models.DateTimeField(null=True)),
                ('num_voters', models.IntegerField(null=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoteXX.toyelection')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=50)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VoteXX.toyelection')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VoteXX_auth.user')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, VoteXX.datatypes.LDObjectContainer),
        ),
    ]
