# Generated by Django 4.2.2 on 2023-07-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BB_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.BigIntegerField()),
                ('key_type', models.BooleanField()),
            ],
        ),
    ]
