# Generated by Django 4.2.2 on 2023-07-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BulletinBoard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bb_data',
            name='id',
        ),
        migrations.AlterField(
            model_name='bb_data',
            name='public_key',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
