# Generated by Django 4.2.2 on 2023-07-31 12:45

import VoteXX_auth.jsonfield
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200, null=True)),
                ('info', VoteXX_auth.jsonfield.JSONField()),
                ('token', VoteXX_auth.jsonfield.JSONField(null=True)),
                ('admin_p', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('user_type', 'user_id')},
            },
        ),
    ]
